 SUBROUTINE FUNC(NDIM,U,ICP,PAR,IJAC,F,DFDU,DFDP)
!---------- ----

	IMPLICIT NONE
	INTEGER, INTENT(IN) :: NDIM, IJAC, ICP(*)
	DOUBLE PRECISION, INTENT(IN) :: U(NDIM), PAR(*)
	DOUBLE PRECISION, INTENT(OUT) :: F(NDIM)
	DOUBLE PRECISION, INTENT(INOUT) :: DFDU(NDIM,*), DFDP(NDIM,*)

	DOUBLE PRECISION x,y,xp,yp,lambda,mu,dP3, dM3, m

	x  = U(1)
	y  = U(2)
	xp = U(3)
	yp = U(4)

	lambda = PAR(1)
	mu     = PAR(2)


	dP3 = SQRT((x-1)**2 + y**2)**3
	dM3 = SQRT((x+1)**2 + y**2)**3
	F(1) = xp
	F(2) = yp
	F(3) =  - (x-1)/dP3-1.5*(x+1)/dM3 + lambda*xp
	F(4) = - y/dP3-1.5*y/dM3+ lambda*yp

 END SUBROUTINE FUNC

 SUBROUTINE STPNT(NDIM,U,PAR,T)
!---------- -----

	IMPLICIT NONE
	INTEGER, INTENT(IN) :: NDIM
	DOUBLE PRECISION, INTENT(INOUT) :: U(NDIM), PAR(*)
	DOUBLE PRECISION, INTENT(IN) :: T

	DOUBLE PRECISION lambda,mu


	lambda = 0d0
	mu     = +1d-1

	PAR(1) = lambda
	PAR(2) = mu



	U(1) = (SQRT(1.5)-1)/(SQRT(1.5)+1)
	U(2) = 0d0
	U(3) = 0d0
	U(4) = 0d0

 END SUBROUTINE STPNT

 SUBROUTINE BCND(NDIM,PAR,ICP,NBC,U0,U1,FB,IJAC,DBC)

 	IMPLICIT NONE
 	INTEGER, INTENT(IN) :: NDIM, ICP(*), NBC, IJAC
 	DOUBLE PRECISION, INTENT(IN) :: PAR(*), U0(NDIM), U1(NDIM)
 	DOUBLE PRECISION, INTENT(OUT) :: FB(NBC)
 	DOUBLE PRECISION, INTENT(INOUT) :: DBC(NBC,*)

 	FB(1) = U0(2)
 	FB(2) = U0(3)
 	FB(3) = U1(3)
 	FB(4) = U1(4)

 END SUBROUTINE BCND

 SUBROUTINE ICND
 END SUBROUTINE ICND

 SUBROUTINE PVLS
 END SUBROUTINE PVLS

 SUBROUTINE FOPT
 END SUBROUTINE FOPT
